# Generated by Django 3.1.1 on 2020-09-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=255, null=True)),
                ('checksum', models.CharField(blank=True, max_length=8, null=True)),
                ('qrcodexml', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='registered', max_length=32)),
                ('athlete', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='run.athlete')),
            ],
            options={
                'verbose_name': 'Run',
                'unique_together': {('athlete', 'date')},
            },
        ),
    ]
