# Generated by Django 3.1.1 on 2020-09-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=255, null=True)),
                ('checksum', models.CharField(blank=True, max_length=8, null=True)),
                ('qrcodexml', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
