# Generated by Django 3.1.1 on 2020-09-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='time',
            field=models.TimeField(default='18:00'),
        ),
    ]
