# Generated by Django 3.1.1 on 2020-09-12 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField()),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='registered', max_length=32)),
                ('athlete_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='run.athlete')),
            ],
        ),
    ]
