# Generated by Django 3.1.1 on 2020-09-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0002_runs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='athlete_id',
            field=models.IntegerField(),
        ),
    ]
