# Generated by Django 3.1.1 on 2020-09-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0003_auto_20200912_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runs',
            old_name='week',
            new_name='date',
        ),
    ]
