# Generated by Django 3.1.1 on 2020-09-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0004_auto_20200912_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runs',
            options={'verbose_name': 'Run'},
        ),
        migrations.AlterUniqueTogether(
            name='runs',
            unique_together={('athlete_id', 'date')},
        ),
    ]
